context:
  name: testscenarios
  version: "0.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/testscenarios/testscenarios-${{ version }}.tar.gz
  sha256: edea4e461cb55a25e050e8352e2a9b5e1fe9d36c10121047120a82acd3e465a3
  patches:
    - remove-fix-tests.patch

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pbr >=0.11
    - pip
    - hatchling
  run:
    - pbr >=0.11
    - python >=${{ python_min }}
    - testtools

tests:
  - python:
      imports:
        - testscenarios
        - testscenarios.scenarios
        - testscenarios.testcase
        - testscenarios.tests
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - if: unix
        then:
          - mkdir -p ${PREFIX}/__hack__
          - cp -r doc/ README ${PREFIX}/__hack__
          - python -m testtools.run testscenarios.test_suite
        else:
          - echo "Skip hacky test"
          # - mkdir -p %PREFIX%\__hack__
          # - cp -r doc README %PREFIX%\__hack__
          # - python -m testtools.run testscenarios.test_suite
    requirements:
      run:
        - python >=${{ python_min }}
    files:
      source:
        - README
        - doc/



about:
  homepage: https://github.com/testing-cabal/testscenarios
  summary: 'Testscenarios, a pyunit extension for dependency injection'
  description: |
    testscenarios provides clean dependency injection for python unittest
    style tests. This can be used for interface testing (testing many
    implementations via a single test suite) or for classic dependency
    injection (provide tests with dependencies externally to the test code
    itself, allowing easy testing in different situations).
  license: BSD-3-Clause
  license_file: BSD
  repository: https://github.com/testing-cabal/testscenarios

extra:
  recipe-maintainers:
    - MementoRC
